champions_dmg_profile = {
    "Aatrox": {
        "GPM": 381,
        "DPM": 383,
        "physical_damage": 94.4,
        "magic_damage": 2.9,
        "true_damage": 2.8,
    },
    "Ahri": {
        "GPM": 392,
        "DPM": 494,
        "physical_damage": 6.4,
        "magic_damage": 69.5,
        "true_damage": 24.1,
    },
    "Akali": {
        "GPM": 393,
        "DPM": 431,
        "physical_damage": 13.9,
        "magic_damage": 83.0,
        "true_damage": 3.1,
    },
    "Akshan": {
        "GPM": 390,
        "DPM": 429,
        "physical_damage": 80.0,
        "magic_damage": 14.8,
        "true_damage": 5.2,
    },
    "Alistar": {
        "GPM": 242,
        "DPM": 115,
        "physical_damage": 12.1,
        "magic_damage": 74.2,
        "true_damage": 13.7,
    },
    "Amumu": {
        "GPM": 240,
        "DPM": 176,
        "physical_damage": 9.1,
        "magic_damage": 74.8,
        "true_damage": 16.1,
    },
    "Anivia": {
        "GPM": 385,
        "DPM": 471,
        "physical_damage": 3.5,
        "magic_damage": 94.6,
        "true_damage": 1.9,
    },
    "Annie": {
        "GPM": 239,
        "DPM": 203,
        "physical_damage": 9.6,
        "magic_damage": 81.5,
        "true_damage": 8.9,
    },
    "Aphelios": {
        "GPM": 437,
        "DPM": 512,
        "physical_damage": 90,
        "magic_damage": 5.7,
        "true_damage": 4.3,
    },
    "Ashe": {
        "GPM": 406,
        "DPM": 473,
        "physical_damage": 85.8,
        "magic_damage": 11.1,
        "true_damage": 3.2,
    },
    "Aurelion Sol": {
        "GPM": 395,
        "DPM": 513,
        "physical_damage": 4.5,
        "magic_damage": 93.9,
        "true_damage": 1.7,
    },
    "Azir": {
        "GPM": 406,
        "DPM": 557,
        "physical_damage": 3.0,
        "magic_damage": 95.6,
        "true_damage": 1.4,
    },
    "Bard": {
        "GPM": 252,
        "DPM": 190,
        "physical_damage": 18.8,
        "magic_damage": 74.9,
        "true_damage": 6.3,
    },
    "Bel'Veth": {
        "GPM": 354,
        "DPM": 265,
        "physical_damage": 58.0,
        "magic_damage": 17.8,
        "true_damage": 24.2,
    },
    "Blitzcrank": {
        "GPM": 249,
        "DPM": 149,
        "physical_damage": 25.2,
        "magic_damage": 61.7,
        "true_damage": 13.1,
    },
    "Brand": {
        "GPM": 298,
        "DPM": 478,
        "physical_damage": 2.2,
        "magic_damage": 95.4,
        "true_damage": 2.4,
    },
    "Braum": {
        "GPM": 250,
        "DPM": 140,
        "physical_damage": 10.3,
        "magic_damage": 84.3,
        "true_damage": 5.4,
    },
    "Caitlyn": {
        "GPM": 417,
        "DPM": 551,
        "physical_damage": 85.7,
        "magic_damage": 11,
        "true_damage": 3.3,
    },
    "Camille": {
        "GPM": 384,
        "DPM": 371,
        "physical_damage": 67.3,
        "magic_damage": 5.8,
        "true_damage": 26.9,
    },
    "Cassiopeia": {
        "GPM": 399,
        "DPM": 485,
        "physical_damage": 1.9,
        "magic_damage": 96.7,
        "true_damage": 1.4,
    },
    "Cho'Gath": {
        "GPM": 360,
        "DPM": 346,
        "physical_damage": 13.8,
        "magic_damage": 64.9,
        "true_damage": 21.3,
    },
    "Corki": {
        "GPM": 419,
        "DPM": 631,
        "physical_damage": 16.5,
        "magic_damage": 80.5,
        "true_damage": 3.1,
    },
    "Darius": {
        "GPM": 376,
        "DPM": 335,
        "physical_damage": 75.9,
        "magic_damage": 0.6,
        "true_damage": 23.5,
    },
    "Diana": {
        "GPM": 373,
        "DPM": 397,
        "physical_damage": 7.3,
        "magic_damage": 89.1,
        "true_damage": 3.6,
    },
    "Dr. Mundo": {
        "GPM": 360,
        "DPM": 418,
        "physical_damage": 20.5,
        "magic_damage": 78.6,
        "true_damage": 0.9,
    },
    "Draven": {
        "GPM": 469,
        "DPM": 486,
        "physical_damage": 95.2,
        "magic_damage": 1.4,
        "true_damage": 3.4,
    },
    "Ekko": {
        "GPM": 377,
        "DPM": 411,
        "physical_damage": 22.2,
        "magic_damage": 75.8,
        "true_damage": 2.0,
    },
    "Elise": {
        "GPM": 327,
        "DPM": 301,
        "physical_damage": 8.5,
        "magic_damage": 88.1,
        "true_damage": 3.4,
    },
    "Evelynn": {
        "GPM": 302,
        "DPM": 314,
        "physical_damage": 22.5,
        "magic_damage": 72.3,
        "true_damage": 5.2,
    },
    "Ezreal": {
        "GPM": 423,
        "DPM": 660,
        "physical_damage": 66.1,
        "magic_damage": 30.3,
        "true_damage": 3.6,
    },
    "Fiddlesticks": {
        "GPM": 256,
        "DPM": 267,
        "physical_damage": 2.8,
        "magic_damage": 90.4,
        "true_damage": 6.8,
    },
    "Fiora": {
        "GPM": 406,
        "DPM": 430,
        "physical_damage": 63.6,
        "magic_damage": 6,
        "true_damage": 30.4,
    },
    "Fizz": {
        "GPM": 369,
        "DPM": 395,
        "physical_damage": 26.2,
        "magic_damage": 68.7,
        "true_damage": 5.1,
    },
    "Galio": {
        "GPM": 333,
        "DPM": 324,
        "physical_damage": 1.4,
        "magic_damage": 95.3,
        "true_damage": 3.3,
    },
    "Gangplank": {
        "GPM": 438,
        "DPM": 600,
        "physical_damage": 63.4,
        "magic_damage": 26,
        "true_damage": 10.7,
    },
    "Garen": {
        "GPM": 370,
        "DPM": 257,
        "physical_damage": 69.5,
        "magic_damage": 17.6,
        "true_damage": 12.9,
    },
    "Gnar": {
        "GPM": 381,
        "DPM": 451,
        "physical_damage": 82.1,
        "magic_damage": 16.8,
        "true_damage": 1.1,
    },
    "Gragas": {
        "GPM": 317,
        "DPM": 306,
        "physical_damage": 9.2,
        "magic_damage": 87.4,
        "true_damage": 3.4,
    },
    "Graves": {
        "GPM": 375,
        "DPM": 395,
        "physical_damage": 88.0,
        "magic_damage": 7.5,
        "true_damage": 4.5,
    },
    "Gwen": {
        "GPM": 396,
        "DPM": 467,
        "physical_damage": 14.1,
        "magic_damage": 56.2,
        "true_damage": 29.7,
    },
    "Hecarim": {
        "GPM": 349,
        "DPM": 311,
        "physical_damage": 68.2,
        "magic_damage": 24.1,
        "true_damage": 7.7,
    },
    "Heimerdinger": {
        "GPM": 386,
        "DPM": 622,
        "physical_damage": 4.5,
        "magic_damage": 94.4,
        "true_damage": 1.1,
    },
    "Illaoi": {
        "GPM": 378,
        "DPM": 554,
        "physical_damage": 97.0,
        "magic_damage": 2.2,
        "true_damage": 0.8,
    },
    "Irelia": {
        "GPM": 398,
        "DPM": 366,
        "physical_damage": 59.8,
        "magic_damage": 29.3,
        "true_damage": 10.9,
    },
    "Ivern": {
        "GPM": 320,
        "DPM": 161,
        "physical_damage": 26.5,
        "magic_damage": 54.4,
        "true_damage": 19.1,
    },
    "Janna": {
        "GPM": 266,
        "DPM": 92,
        "physical_damage": 18.7,
        "magic_damage": 73.9,
        "true_damage": 7.5,
    },
    "Jarvan IV": {
        "GPM": 323,
        "DPM": 218,
        "physical_damage": 80.0,
        "magic_damage": 14.4,
        "true_damage": 5.7,
    },
    "Jax": {
        "GPM": 382,
        "DPM": 329,
        "physical_damage": 69.9,
        "magic_damage": 26.5,
        "true_damage": 3.6,
    },
    "Jayce": {
        "GPM": 405,
        "DPM": 595,
        "physical_damage": 87.0,
        "magic_damage": 11.8,
        "true_damage": 1.3,
    },
    "Jhin": {
        "GPM": 401,
        "DPM": 512,
        "physical_damage": 84.9,
        "magic_damage": 13.3,
        "true_damage": 1.9,
    },
    "Jinx": {
        "GPM": 440,
        "DPM": 551,
        "physical_damage": 86.9,
        "magic_damage": 6.5,
        "true_damage": 6.6,
    },
    "Kai'Sa": {
        "GPM": 444,
        "DPM": 477,
        "physical_damage": 59.9,
        "magic_damage": 34.7,
        "true_damage": 5.4,
    },
    "Kalista": {
        "GPM": 426,
        "DPM": 418,
        "physical_damage": 89.7,
        "magic_damage": 6.7,
        "true_damage": 3.6,
    },
    "Karma": {
        "GPM": 287,
        "DPM": 264,
        "physical_damage": 9.5,
        "magic_damage": 86.5,
        "true_damage": 4.0,
    },
    "Karthus": {
        "GPM": 370,
        "DPM": 561,
        "physical_damage": 0.6,
        "magic_damage": 95.6,
        "true_damage": 3.8,
    },
    "Kassadin": {
        "GPM": 393,
        "DPM": 517,
        "physical_damage": 6.6,
        "magic_damage": 91.9,
        "true_damage": 1.5,
    },
    "Katarina": {
        "GPM": 380,
        "DPM": 469,
        "physical_damage": 5.6,
        "magic_damage": 91.1,
        "true_damage": 3.4,
    },
    "Kayle": {
        "GPM": 393,
        "DPM": 436,
        "physical_damage": 26.7,
        "magic_damage": 69.1,
        "true_damage": 4.3,
    },
    "Kayn": {
        "GPM": 359,
        "DPM": 354,
        "physical_damage": 88.1,
        "magic_damage": 4.9,
        "true_damage": 7.0,
    },
    "Kennen": {
        "GPM": 379,
        "DPM": 455,
        "physical_damage": 25.0,
        "magic_damage": 73.3,
        "true_damage": 1.7,
    },
    "Kha'Zix": {
        "GPM": 337,
        "DPM": 324,
        "physical_damage": 86.4,
        "magic_damage": 9.4,
        "true_damage": 4.2,
    },
    "Kindred": {
        "GPM": 353,
        "DPM": 347,
        "physical_damage": 75.6,
        "magic_damage": 16.6,
        "true_damage": 7.8,
    },
    "Kled": {
        "GPM": 385,
        "DPM": 373,
        "physical_damage": 96.6,
        "magic_damage": 0.6,
        "true_damage": 2.8,
    },
    "Kog'Maw": {
        "GPM": 403,
        "DPM": 628,
        "physical_damage": 39.2,
        "magic_damage": 53.3,
        "true_damage": 7.5,
    },
    "LeBlanc": {
        "GPM": 384,
        "DPM": 529,
        "physical_damage": 7.2,
        "magic_damage": 90.0,
        "true_damage": 2.8,
    },
    "Lee Sin": {
        "GPM": 332,
        "DPM": 251,
        "physical_damage": 80.9,
        "magic_damage": 14.9,
        "true_damage": 4.2,
    },
    "Leona": {
        "GPM": 233,
        "DPM": 112,
        "physical_damage": 23.5,
        "magic_damage": 60.2,
        "true_damage": 16.3,
    },
    "Lillia": {
        "GPM": 351,
        "DPM": 402,
        "physical_damage": 3.3,
        "magic_damage": 70.7,
        "true_damage": 26.0,
    },
    "Lissandra": {
        "GPM": 387,
        "DPM": 430,
        "physical_damage": 6.2,
        "magic_damage": 92.6,
        "true_damage": 1.2,
    },
    "Lucian": {
        "GPM": 413,
        "DPM": 506,
        "physical_damage": 85.2,
        "magic_damage": 12.4,
        "true_damage": 2.4,
    },
    "Lulu": {
        "GPM": 298,
        "DPM": 230,
        "physical_damage": 12.5,
        "magic_damage": 82.1,
        "true_damage": 5.4,
    },
    "Lux": {
        "GPM": 264,
        "DPM": 260,
        "physical_damage": 8.1,
        "magic_damage": 87.9,
        "true_damage": 4.0,
    },
    "Malphite": {
        "GPM": 344,
        "DPM": 358,
        "physical_damage": 22.8,
        "magic_damage": 76.4,
        "true_damage": 0.8,
    },
    "Malzahar": {
        "GPM": 342,
        "DPM": 413,
        "physical_damage": 8.1,
        "magic_damage": 89.9,
        "true_damage": 2,
    },
    "Maokai": {
        "GPM": 336,
        "DPM": 361,
        "physical_damage": 12.5,
        "magic_damage": 86.5,
        "true_damage": 1.0,
    },
    "Master Yi": {
        "GPM": 439,
        "DPM": 418,
        "physical_damage": 63.0,
        "magic_damage": 2.8,
        "true_damage": 34.2,
    },
    "Miss Fortune": {
        "GPM": 417,
        "DPM": 501,
        "physical_damage": 83.7,
        "magic_damage": 13.2,
        "true_damage": 3.1,
    },
    "Mordekaiser": {
        "GPM": 371,
        "DPM": 418,
        "physical_damage": 11.4,
        "magic_damage": 86.1,
        "true_damage": 2.6,
    },
    "Morgana": {
        "GPM": 267,
        "DPM": 244,
        "physical_damage": 6.7,
        "magic_damage": 86.9,
        "true_damage": 6.4,
    },
    "Nami": {
        "GPM": 248,
        "DPM": 148,
        "physical_damage": 16.1,
        "magic_damage": 76.7,
        "true_damage": 7.2,
    },
    "Nasus": {
        "GPM": 391,
        "DPM": 494,
        "physical_damage": 51.1,
        "magic_damage": 47.9,
        "true_damage": 1.0,
    },
    "Nautilus": {
        "GPM": 255,
        "DPM": 180,
        "physical_damage": 20.2,
        "magic_damage": 71.6,
        "true_damage": 8.2,
    },
    "Neeko": {
        "GPM": 374,
        "DPM": 408,
        "physical_damage": 20.3,
        "magic_damage": 77.4,
        "true_damage": 2.3,
    },
    "Nidalee": {
        "GPM": 368,
        "DPM": 421,
        "physical_damage": 6.5,
        "magic_damage": 90.6,
        "true_damage": 2.9,
    },
    "Nilah": {
        "GPM": 0,
        "DPM": 0,
        "physical_damage": 0,
        "magic_damage": 0,
        "true_damage": 0,
    },
    "Nocturne": {
        "GPM": 343,
        "DPM": 285,
        "physical_damage": 86.0,
        "magic_damage": 9.3,
        "true_damage": 4.7,
    },
    "Nunu": {
        "GPM": 291,
        "DPM": 147,
        "physical_damage": 10.6,
        "magic_damage": 86.8,
        "true_damage": 2.7,
    },
    "Olaf": {
        "GPM": 338,
        "DPM": 305,
        "physical_damage": 65.5,
        "magic_damage": 2.8,
        "true_damage": 31.7,
    },
    "Orianna": {
        "GPM": 400,
        "DPM": 484,
        "physical_damage": 4.1,
        "magic_damage": 94.7,
        "true_damage": 1.2,
    },
    "Ornn": {
        "GPM": 342,
        "DPM": 350,
        "physical_damage": 34.6,
        "magic_damage": 63.4,
        "true_damage": 2.0,
    },
    "Pantheon": {
        "GPM": 318,
        "DPM": 313,
        "physical_damage": 83.4,
        "magic_damage": 10.7,
        "true_damage": 5.9,
    },
    "Poppy": {
        "GPM": 345,
        "DPM": 327,
        "physical_damage": 71.8,
        "magic_damage": 25.9,
        "true_damage": 2.3,
    },
    "Pyke": {
        "GPM": 286,
        "DPM": 169,
        "physical_damage": 76.7,
        "magic_damage": 1.9,
        "true_damage": 21.4,
    },
    "Qiyana": {
        "GPM": 373,
        "DPM": 418,
        "physical_damage": 89.0,
        "magic_damage": 6.7,
        "true_damage": 4.3,
    },
    "Quinn": {
        "GPM": 413,
        "DPM": 546,
        "physical_damage": 89.8,
        "magic_damage": 6.7,
        "true_damage": 3.5,
    },
    "Rakan": {
        "GPM": 247,
        "DPM": 143,
        "physical_damage": 13.8,
        "magic_damage": 74.6,
        "true_damage": 11.6,
    },
    "Rammus": {
        "GPM": 361,
        "DPM": 411,
        "physical_damage": 20.2,
        "magic_damage": 79.3,
        "true_damage": 0.5,
    },
    "Rek'Sai": {
        "GPM": 333,
        "DPM": 257,
        "physical_damage": 57.0,
        "magic_damage": 30.2,
        "true_damage": 12.8,
    },
    "Rell": {
        "GPM": 229,
        "DPM": 138,
        "physical_damage": 8.4,
        "magic_damage": 78.4,
        "true_damage": 13.2,
    },
    "Renata Glasc": {
        "GPM": 243,
        "DPM": 163,
        "physical_damage": 15.9,
        "magic_damage": 58.7,
        "true_damage": 25.4,
    },
    "Renekton": {
        "GPM": 384,
        "DPM": 358,
        "physical_damage": 85.0,
        "magic_damage": 13.3,
        "true_damage": 1.7,
    },
    "Rengar": {
        "GPM": 347,
        "DPM": 277,
        "physical_damage": 77.6,
        "magic_damage": 19.4,
        "true_damage": 3.0,
    },
    "Riven": {
        "GPM": 388,
        "DPM": 322,
        "physical_damage": 94.6,
        "magic_damage": 0.9,
        "true_damage": 4.5,
    },
    "Rumble": {
        "GPM": 357,
        "DPM": 519,
        "physical_damage": 2.3,
        "magic_damage": 96.0,
        "true_damage": 1.7,
    },
    "Ryze": {
        "GPM": 406,
        "DPM": 431,
        "physical_damage": 3.9,
        "magic_damage": 95.1,
        "true_damage": 1,
    },
    "Samira": {
        "GPM": 421,
        "DPM": 383,
        "physical_damage": 86.1,
        "magic_damage": 10.9,
        "true_damage": 3.0,
    },
    "Sejuani": {
        "GPM": 317,
        "DPM": 217,
        "physical_damage": 47.6,
        "magic_damage": 45.4,
        "true_damage": 7,
    },
    "Senna": {
        "GPM": 336,
        "DPM": 459,
        "physical_damage": 93.6,
        "magic_damage": 1.6,
        "true_damage": 4.8,
    },
    "Seraphine": {
        "GPM": 325,
        "DPM": 310,
        "physical_damage": 11.0,
        "magic_damage": 87.5,
        "true_damage": 1.5,
    },
    "Sett": {
        "GPM": 324,
        "DPM": 313,
        "physical_damage": 72.0,
        "magic_damage": 3.8,
        "true_damage": 24.2,
    },
    "Shaco": {
        "GPM": 343,
        "DPM": 334,
        "physical_damage": 50.9,
        "magic_damage": 41.2,
        "true_damage": 8.0,
    },
    "Shen": {
        "GPM": 332,
        "DPM": 251,
        "physical_damage": 51.3,
        "magic_damage": 45.4,
        "true_damage": 3.3,
    },
    "Shyvana": {
        "GPM": 345,
        "DPM": 407,
        "physical_damage": 27.8,
        "magic_damage": 69.2,
        "true_damage": 8.0,
    },
    "Singed": {
        "GPM": 372,
        "DPM": 371,
        "physical_damage": 3.1,
        "magic_damage": 96.1,
        "true_damage": 0.8,
    },
    "Sion": {
        "GPM": 346,
        "DPM": 345,
        "physical_damage": 58.1,
        "magic_damage": 40.8,
        "true_damage": 1.2,
    },
    "Sivir": {
        "GPM": 427,
        "DPM": 562,
        "physical_damage": 94.1,
        "magic_damage": 3.5,
        "true_damage": 2.4,
    },
    "Skarner": {
        "GPM": 313,
        "DPM": 136,
        "physical_damage": 43.3,
        "magic_damage": 38.5,
        "true_damage": 18.2,
    },
    "Sona": {
        "GPM": 329,
        "DPM": 304,
        "physical_damage": 13.1,
        "magic_damage": 84.5,
        "true_damage": 2.4,
    },
    "Soraka": {
        "GPM": 261,
        "DPM": 155,
        "physical_damage": 10.5,
        "magic_damage": 83.4,
        "true_damage": 6.1,
    },
    "Swain": {
        "GPM": 381,
        "DPM": 498,
        "physical_damage": 7.4,
        "magic_damage": 91.0,
        "true_damage": 1.6,
    },
    "Sylas": {
        "GPM": 383,
        "DPM": 428,
        "physical_damage": 4.1,
        "magic_damage": 93.6,
        "true_damage": 2.3,
    },
    "Syndra": {
        "GPM": 395,
        "DPM": 520,
        "physical_damage": 3.7,
        "magic_damage": 93.4,
        "true_damage": 2.9,
    },
    "Tahm Kench": {
        "GPM": 259,
        "DPM": 136,
        "physical_damage": 9.4,
        "magic_damage": 85.2,
        "true_damage": 5.4,
    },
    "Taliyah": {
        "GPM": 391,
        "DPM": 526,
        "physical_damage": 2.8,
        "magic_damage": 94.6,
        "true_damage": 2.6,
    },
    "Talon": {
        "GPM": 400,
        "DPM": 434,
        "physical_damage": 94.1,
        "magic_damage": 1.4,
        "true_damage": 4.5,
    },
    "Taric": {
        "GPM": 255,
        "DPM": 82,
        "physical_damage": 24.0,
        "magic_damage": 66.0,
        "true_damage": 10.0,
    },
    "Teemo": {
        "GPM": 365,
        "DPM": 562,
        "physical_damage": 9.3,
        "magic_damage": 86.8,
        "true_damage": 3.9,
    },
    "Thresh": {
        "GPM": 238,
        "DPM": 115,
        "physical_damage": 12.1,
        "magic_damage": 74.1,
        "true_damage": 13.8,
    },
    "Tristana": {
        "GPM": 430,
        "DPM": 513,
        "physical_damage": 73.8,
        "magic_damage": 20.5,
        "true_damage": 5.7,
    },
    "Trundle": {
        "GPM": 314,
        "DPM": 192,
        "physical_damage": 61.0,
        "magic_damage": 32.6,
        "true_damage": 6.4,
    },
    "Tryndamere": {
        "GPM": 426,
        "DPM": 381,
        "physical_damage": 91.1,
        "magic_damage": 6.1,
        "true_damage": 2.8,
    },
    "Twisted Fate": {
        "GPM": 419,
        "DPM": 434,
        "physical_damage": 9.2,
        "magic_damage": 88.5,
        "true_damage": 2.3,
    },
    "Twitch": {
        "GPM": 397,
        "DPM": 577,
        "physical_damage": 80.3,
        "magic_damage": 3.6,
        "true_damage": 16.1,
    },
    "Udyr": {
        "GPM": 341,
        "DPM": 203,
        "physical_damage": 36.8,
        "magic_damage": 51.2,
        "true_damage": 12.0,
    },
    "Urgot": {
        "GPM": 384,
        "DPM": 383,
        "physical_damage": 89.1,
        "magic_damage": 2.1,
        "true_damage": 8.8,
    },
    "Varus": {
        "GPM": 412,
        "DPM": 555,
        "physical_damage": 79.1,
        "magic_damage": 18.9,
        "true_damage": 2.0,
    },
    "Vayne": {
        "GPM": 411,
        "DPM": 461,
        "physical_damage": 68.9,
        "magic_damage": 5.8,
        "true_damage": 25.3,
    },
    "Veigar": {
        "GPM": 386,
        "DPM": 422,
        "physical_damage": 3.0,
        "magic_damage": 95.8,
        "true_damage": 1.2,
    },
    "Vel'Koz": {
        "GPM": 378,
        "DPM": 614,
        "physical_damage": 1.4,
        "magic_damage": 77.2,
        "true_damage": 21.4,
    },
    "Vex": {
        "GPM": 373,
        "DPM": 445,
        "physical_damage": 6.9,
        "magic_damage": 90.7,
        "true_damage": 2.4,
    },
    "Vi": {
        "GPM": 307,
        "DPM": 223,
        "physical_damage": 90.6,
        "magic_damage": 2.6,
        "true_damage": 6.8,
    },
    "Viego": {
        "GPM": 356,
        "DPM": 310,
        "physical_damage": 82.1,
        "magic_damage": 12.2,
        "true_damage": 5.7,
    },
    "Viktor": {
        "GPM": 396,
        "DPM": 619,
        "physical_damage": 1.4,
        "magic_damage": 97.5,
        "true_damage": 1.1,
    },
    "Vladimir": {
        "GPM": 394,
        "DPM": 515,
        "physical_damage": 4.2,
        "magic_damage": 94.2,
        "true_damage": 1.6,
    },
    "Volibear": {
        "GPM": 322,
        "DPM": 271,
        "physical_damage": 55.0,
        "magic_damage": 37.9,
        "true_damage": 7.2,
    },
    "Warwick": {
        "GPM": 345,
        "DPM": 236,
        "physical_damage": 33.2,
        "magic_damage": 62.3,
        "true_damage": 4.5,
    },
    "Wukong": {
        "GPM": 359,
        "DPM": 339,
        "physical_damage": 80.7,
        "magic_damage": 15.6,
        "true_damage": 3.8,
    },
    "Xayah": {
        "GPM": 438,
        "DPM": 535,
        "physical_damage": 91.9,
        "magic_damage": 4.6,
        "true_damage": 3.6,
    },
    "Xerath": {
        "GPM": 364,
        "DPM": 743,
        "physical_damage": 1.0,
        "magic_damage": 98.0,
        "true_damage": 1.0,
    },
    "Xin Zhao": {
        "GPM": 327,
        "DPM": 291,
        "physical_damage": 85.0,
        "magic_damage": 8.6,
        "true_damage": 6.4,
    },
    "Yasuo": {
        "GPM": 402,
        "DPM": 351,
        "physical_damage": 74.9,
        "magic_damage": 13.7,
        "true_damage": 11.4,
    },
    "Yone": {
        "GPM": 408,
        "DPM": 420,
        "physical_damage": 62.2,
        "magic_damage": 23.5,
        "true_damage": 14.4,
    },
    "Yorick": {
        "GPM": 398,
        "DPM": 421,
        "physical_damage": 55.2,
        "magic_damage": 38.4,
        "true_damage": 6.4,
    },
    "Yuumi": {
        "GPM": 239,
        "DPM": 281,
        "physical_damage": 8.3,
        "magic_damage": 85.0,
        "true_damage": 6.7,
    },
    "Zac": {
        "GPM": 314,
        "DPM": 192,
        "physical_damage": 8.3,
        "magic_damage": 82.9,
        "true_damage": 8.8,
    },
    "Zed": {
        "GPM": 389,
        "DPM": 487,
        "physical_damage": 88.2,
        "magic_damage": 6.6,
        "true_damage": 5.2,
    },
    "Zeri": {
        "GPM": 456,
        "DPM": 568,
        "physical_damage": 55.9,
        "magic_damage": 40.6,
        "true_damage": 3.5,
    },
    "Ziggs": {
        "GPM": 395,
        "DPM": 684,
        "physical_damage": 2.5,
        "magic_damage": 96.6,
        "true_damage": 0.9,
    },
    "Zilean": {
        "GPM": 342,
        "DPM": 367,
        "physical_damage": 6.0,
        "magic_damage": 91.7,
        "true_damage": 2.3,
    },
    "Zoe": {
        "GPM": 382,
        "DPM": 563,
        "physical_damage": 6.3,
        "magic_damage": 83.2,
        "true_damage": 10.5,
    },
    "Zyra": {
        "GPM": 272,
        "DPM": 375,
        "physical_damage": 5.7,
        "magic_damage": 90.9,
        "true_damage": 3.4,
    },
}
